<?php

namespace app\models;

require_once dirname(__FILE__) . '/../../../../models/Auth.php';

/**
 * Test class for Auth.
 * Generated by PHPUnit on 2010-12-17 at 08:25:59.
 */
class AuthTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Auth
	 */
	protected $auth;

	protected function setUp() {
		$this->auth = new Auth;
	}

	protected function tearDown() {
		unset($this->auth);
	}

	public function testAuth() {
		$this->auth->setLogin('MyUser');
		$this->auth->setPassword('secret');

		$this->assertEquals('MyUser:secret', $this->auth->__toString());
	}

}

?>
