<?php

namespace app\models;

/**
 * Test class for Auth.
 * Generated by PHPUnit on 2010-12-17 at 08:25:59.
 */
class AuthTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Auth
	 */
	protected $auth;

	protected function setUp() {
		$this->auth = Auth::create();
	}

	protected function tearDown() {
		unset($this->auth);
	}

	public function testAuth() {
		$this->auth->login = 'MyUser';
		$this->auth->password = 'secret';
		$this->auth->save();
		$testAuth = Auth::find('first', array(
				'conditions' => array(
					'login' => 'MyUser'
				)
			)
		);
		$this->assertEquals('MyUser', $testAuth->login);
		$this->assertEquals('secret', $testAuth->password);

	}

}

?>
