<?php

namespace app\models;

//require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../../models/Schedule.php';

/**
 * Test class for Schedule.
 * Generated by PHPUnit on 2010-12-16 at 16:58:46.
 */
class ScheduleTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Schedule
	 */
	protected $schedule;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->schedule = new Schedule;
	}

	protected function tearDown() {
		unset($this->schedule);
	}

	public function testSchedule() {
		$this->schedule->setPlace('Adore Grill');
		$this->schedule->setRepeat();
		$this->schedule->setDate("16/12/2010");
		$this->schedule->setTime("12:15");
		$this->schedule->setDone();
		
		$this->assertEquals('Once 16/12/2010 12:15 Adore Grill', $this->schedule->__toString());
	}


}

?>
